version: "3.8"

services:
  nextjs:
    container_name: my-nextjs-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge
